use tendabd;
select concat(clt_nome, ',' , clt_apelidos) as 'Nombre' , length(clt_nome) from clientes;
select lower(clt_nome) from clientes;
select timestampdiff(year,'1981-03-22',curdate()) as 'Edad';
insert into vendas (ven_tenda, ven_empregado, ven_cliente, ven_data) values (7,2,1,'2019-12-01'),(2,14,30,'2019-12-30'),(2,14,60,'2020-01-3'),(2,14,60,'2020-01-3');
select * from vendas where month(ven_data) between 5 and 6 order by ven_data;
select art_codigo, art_nome, round(art_pv) from artigos where art_color like 'negro';
select avg(art_peso) as 'Media' from artigos;
select avg(art_peso) as 'Media peso', max(art_pv)-min(art_pc) as 'Diferencia máxima' from artigos where art_color is not null;
select count(distinct art_color) from artigos;
select art_nome, ifnull(art_color,'Descoñecido') from artigos;
use traballadores;
select empnome, empdatanacemento, empsalario , timestampdiff(year, empdataingreso,curdate())*empsalario as 'Liquidación' , timestampdiff(year, empdatanacemento,curdate()) as 'Edad' from empregado where timestampdiff(year, empdatanacemento,curdate())>=60; 
select empnome , day(empdatanacemento),month(empdatanacemento) from empregado where empdepartamento=110 or empdepartamento=111;
select count(*), avg(empsalario) from empregado where timestampdiff(year, empdataingreso,curdate())=20;
select empnome,(empsalario+ ifnull(empcomision,0))*14 as 'Salario anual' from empregado order by 2 desc;
select sum((empsalario+ ifnull(empcomision,0))*14) as 'Salario anual' from empregado;
select count(*) , avg(deppresuposto)  from departamento;
select sum(empcomision) from empregado;
select empnome, empdatanacemento, timestampdiff(year, empdatanacemento,curdate()) as 'Edad' from empregado where timestampdiff(year, empdatanacemento,curdate())>=50 order by 3 desc ;
select empnome, date_format(empdataingreso,'%d/%m/%Y') as 'Data ingreso', floor(timestampdiff(year, empdataingreso,curdate())/3) as  'Trienios' from empregado where timestampdiff(year, empdatanacemento,curdate())=60 order by 3 desc;
select avg(timestampdiff(year,empDataNacemento,empDataIngreso)) as 'Media de Edad' from empregado;
select empNome, date_format(empdataingreso,'%d/%m/%Y') as 'Fecha de ingreso', timestampdiff(year,empDataIngreso,now()) as 'Años en la empresa' from empregado where month(empDataNacemento) = month(now());
select max(timestampdiff(day,empdataingreso,curdate())) - min(timestampdiff(day,empdataingreso,curdate())) as 'Diferencia', min(empdataingreso) , max(empdataingreso) from empregado;
select empNumero, empNome, empSalario+empComision as 'SalarioTotal' from empregado where empSalario+empComision > 1800 order by empNumero;