use tendabd;
select * from tendas;
select prv_nome from provedores;
select clt_poboacion from clientes;
select art_pv , art_pv*1.1 from artigos;
select clt_id , clt_apelidos, clt_nome from clientes where clt_poboacion = 'Madrid';
select art_codigo , art_nome , art_peso from artigos where art_peso > 500;
select * from artigos where art_pv >= art_pc*2;
select clt_apelidos , clt_nome , clt_poboacion , clt_desconto from clientes where (clt_poboacion like "Asturias" or clt_poboacion like "Valencia") and (clt_desconto > 2 or clt_desconto = 0);
select * from artigos where art_color like "negro" and art_peso > 5000;
select * from artigos where art_color != "negro" or art_peso <= 5000;
select * from artigos where art_color like "negro" and art_peso > 100 or art_color like "cyan";
select * from artigos where art_pc between 12 and 18;
select * from artigos where art_color like "negro" or art_color like "cyan";
select * from clientes where clt_apelidos like "RO%";
select * from clientes where clt_nome like "B___A";
select * from artigos where art_color is null;
select * from artigos order by art_peso desc;
select art_codigo , art_nome , art_pc , art_pv , art_pv-art_pc as "Marxe" from artigos where art_pc > 3000 order by "Marxe";
select art_nome , art_provedor , art_stock , art_peso from artigos where art_peso <= 1000 order by art_provedor , art_stock desc;
select clt_nome , clt_apelidos from clientes where clt_apelidos like "F%Z";
select * from artigos where art_nome like binary "%LED%";
select * from artigos where art_nome like binary "CABI%";
select * from artigos;
select * from clientes where clt_apelidos like "a%" or clt_apelidos like "f%" or clt_apelidos like "% a%" or clt_apelidos like "% f%";
select * from clientes where clt_apelidos not like "a%" and clt_apelidos not like "b%" and clt_apelidos not like "c%" and clt_apelidos not like "d%";
select * from artigos where art_pv like "%.00";
select * from clientes where clt_nome like "_____";
use traballadores;
select depNumero , depNome , depDirector from departamento , empregado where empComision > 0.10*empSalario order by depNumero;
select empNome , empSalario , empComision , empFillos , empFillos*30 as "PagaExtra" , empSalario+ifnull(empComision,0)+empFillos*30 as "SueldoTotal" from empregado where empFillos >= 3 order by empNome;
select empNome from empregado where empNome like "MORA%" order by empNome;
select empNome , empFillos+2 as "Invitaciones" , empFillos as "Regalos" from empregado where empNome between "A" and "L" and empFillos > 0;
select empNome , empSalario from empregado where (empFillos = 0 and empSalario > 1200) or (empFillos > 0 and empSalario < 1800);
select empNome , empSalario from empregado where empFillos = 0 order by empSalario desc;
select empNome , empSalario from empregado where empDepartamento = 111 and empComision > 0.15*empSalario order by empNome;
select empNome , empFillos , empSalario , empComision , ifnull(empComision,0)+0.15*empSalario as "ImpNueComision" from empregado where empFillos > 2 order by empNome;